name: Landlord
version: '${project.version}'
main: io.curiositycore.landlord.Landlord
api-version: 1.18
softdepend: [Lands, CoreProtect]
authors: [ RazielMartelus96 ]
description: Add-on for the Lands Plugin that allows for easier monitoring and enforcement of land activity / ownership limits.
commands:
  landlord:
    usage: /landlord <manual_scan_type>
    permission: Landlord.use
    aliases: [lal]
